### ISSUE TITLE
Plugin compile error for UE 4.10.1

### ISSUE THREAD

**Issue by stevenvergenz** [fire/QtCreatorSourceCodeAccess#15]
The following error is generated when I try to compile it for my project. Perhaps the API has changed?

```
In file included from /home/svergenz/Projects/UnrealEngine/Engine/Plugins/Developer/QtCreatorSourceCodeAccess/Intermediate/Build/Linux/x86_64-unknown-linux-gnu/UE4Editor/Development/QtCreatorSourceCodeAccess/Module.QtCreatorSourceCodeAccess.cpp:2:
In file included from /home/svergenz/Projects/UnrealEngine/Engine/Plugins/Developer/QtCreatorSourceCodeAccess/Source/QtCreatorSourceCodeAccess/Private/QtCreatorSourceCodeAccessModule.cpp:25:
/home/svergenz/Projects/UnrealEngine/Engine/Plugins/Developer/QtCreatorSourceCodeAccess/Source/QtCreatorSourceCodeAccess/Private/QtCreatorSourceCodeAccessModule.h:36:31: error: field type 'FQtCreatorSourceCodeAccessor' is an abstract class
        FQtCreatorSourceCodeAccessor QtCreatorSourceCodeAccessor;
                                     ^
Developer/SourceCodeAccess/Public/ISourceCodeAccessor.h:18:15: note: unimplemented pure virtual method 'RefreshAvailability' in 'FQtCreatorSourceCodeAccessor'
        virtual void RefreshAvailability() = 0;
                     ^
In file included from /home/svergenz/Projects/UnrealEngine/Engine/Plugins/Developer/QtCreatorSourceCodeAccess/Intermediate/Build/Linux/x86_64-unknown-linux-gnu/UE4Editor/Development/QtCreatorSourceCodeAccess/Module.QtCreatorSourceCodeAccess.cpp:2:
/home/svergenz/Projects/UnrealEngine/Engine/Plugins/Developer/QtCreatorSourceCodeAccess/Source/QtCreatorSourceCodeAccess/Private/QtCreatorSourceCodeAccessModule.cpp:27:1: error: cannot initialize return object of type 'IModuleInterface *' with an rvalue of type 'FQtCreatorSourceCodeAccessModule *'
IMPLEMENT_MODULE( FQtCreatorSourceCodeAccessModule, QtCreatorSourceCodeAccess );
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Runtime/Core/Public/Modules/ModuleManager.h:683:11: note: expanded from macro 'IMPLEMENT_MODULE'
                        return new ModuleImplClass(); \
                               ^~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

**Comment by fire** [comment]
I'll see if I can find time to switch to Linux and test the Github Unreal Engine Linux build. If you need the changes urgently, the other Github issue has the changes required.

**Comment by stevenvergenz** [comment]
So it's been shown to work with 4.10 then? I'll check the other issues for this.

**Comment by fire** [comment]
Try newest version, if it doesn't work open a bug.
