### ISSUE TITLE
Doesn't work with Unreal Engine 4.1

### ISSUE THREAD

**Issue by shikolad** [fire/QtCreatorSourceCodeAccess#14]
Got error while compiling new version of Unreal Engine under Linux. The error is:

**In file included from /home/shiko/Soft/UnrealEngine-promoted/Engine/Plugins/Developer/QtCreatorSourceCodeAccess/Intermediate/Build/Linux/x86_64-unknown-linux-gnu/UE4Editor/Development/QtCreatorSourceCodeAccess/Module.QtCreatorSourceCodeAccess.cpp:2:
In file included from /home/shiko/Soft/UnrealEngine-promoted/Engine/Plugins/Developer/QtCreatorSourceCodeAccess/Source/QtCreatorSourceCodeAccess/Private/QtCreatorSourceCodeAccessModule.cpp:25:
/home/shiko/Soft/UnrealEngine-promoted/Engine/Plugins/Developer/QtCreatorSourceCodeAccess/Source/QtCreatorSourceCodeAccess/Private/QtCreatorSourceCodeAccessModule.h:36:31: error: field type 'FQtCreatorSourceCodeAccessor' is an abstract class**

Workaround: add new function member to FQtCreatorSourceCodeAccessor class: 
**virtual void RefreshAvailability() override;** //this into QtCreatorSourceCodeAccessor.h file
**void FQtCreatorSourceCodeAccessor::RefreshAvailability(){}** /*this line into QtCreatorSourceCodeAccessor.cpp file */

I'm not sure if the function should be empty but at least this allows the UnrealEditor to compile.

**Comment by fire** [comment]
There is actually a similar change made for the other plugin https://github.com/fire/SensibleEditorSourceCodeAccess/pull/9 Will investigate.

**Comment by fire** [comment]
Please try latest.

**Comment by Keziolio** [comment]
It still doesn't work, but shikolad's fix made it compile and work

**Comment by fire** [comment]
Try newest version, if it doesn't work open a bug.
